services: 

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password
    volumes: db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data: